version: '3'
services:
    
    ribbon2-uix:
        image: freax/ribbon2-uix:3.0
        environment:
            - GATEWAY_URL=http://ribbon2-gateway:9000
        ports:
            - 9999:9999

    ribbon2-gateway:
        image: freax/ribbon2-gateway:3.0
        environment:
            - DB_JDBC_URL=jdbc:postgresql://ribbon2-postgresql:5432/ribbon2-gateway
        depends_on:
            ribbon2-postgresql:
                condition: service_healthy
        ports:
            - 9000:9000
            
    ribbon2-directory:
        image: freax/ribbon2-directory:3.0
        environment:
            - DB_JDBC_URL=jdbc:postgresql://ribbon2-postgresql:5432/ribbon2-directory
            - BRIDGE_CLIENT_ADDRESS=ribbon2-gateway
        depends_on:
            ribbon2-gateway:
                condition: service_started
            
    ribbon2-messenger:
        image: freax/ribbon2-messenger:3.0
        environment:
            - DB_JDBC_URL=jdbc:postgresql://ribbon2-postgresql:5432/ribbon2-messenger
            - BRIDGE_CLIENT_ADDRESS=ribbon2-gateway
        depends_on:
            ribbon2-gateway:
                condition: service_started
            ribbon2-directory:
                condition: service_started
            
    ribbon2-exc-import-rss:
        image: freax/ribbon2-exchanger:3.0
        environment:
            - EXCHANGER_TYPE=IMPORT
            - EXCHANGER_CLASS=tk.freaxsoftware.ribbon2.io.importer.rss.RSSImporter
            - DB_JDBC_URL=jdbc:postgresql://ribbon2-postgresql:5432/ribbon2-exc-import-rss
            - BRIDGE_CLIENT_ADDRESS=ribbon2-gateway
        depends_on:
            ribbon2-gateway:
                condition: service_started
            ribbon2-directory:
                condition: service_started
            ribbon2-messenger:
                condition: service_started

    ribbon2-postgresql:
        image: postgres:11
        environment:
            - POSTGRES_USER=ribbon2
            - POSTGRES_PASSWORD=ribbon2
            - POSTGRES_MULTIPLE_DATABASES="ribbon2-gateway","ribbon2-directory","ribbon2-messenger","ribbon2-exc-import-rss"
        volumes:
            - ./pg-multiple-db:/docker-entrypoint-initdb.d
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 10s
            retries: 5
            
    ribbon2-phppgadmin:
         image: dockage/phppgadmin
         environment:
            - PHP_PG_ADMIN_SERVER_DESC=Ribbon2 DB
            - PHP_PG_ADMIN_SERVER_HOST=ribbon2-postgresql
         ports:
            - 9001:80
